name: Step 2.1, Assign Labels

# This step triggers after the user assigns a label to an issue.
# This workflow updates from step 2.1 to step 2.2.

on:
  workflow_dispatch:
  issues:
    types:
      - labeled

permissions:
  contents: write  # Needed to update the step metadata

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug step file existence
        run: |
          if [ -f ./.github/steps/-step.txt ]; then
            echo "Step file found."
            cat ./.github/steps/-step.txt
          else
            echo "Step file not found!" && exit 1
          fi

      - id: get_step
        run: |
          current_step=$(cat ./.github/steps/-step.txt | tr -d '[:space:]')
          echo "current_step=${current_step}" >> $GITHUB_OUTPUT

      - name: Debug current step
        run: echo "Current step is ${{ steps.get_step.outputs.current_step }}"

    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_labeled_issue:
    name: On labeled issue
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 2.1.
    if: >-
      ${{ github.event_name == 'issues' 
          && !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == '2.1' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: update-game

      - name: Check if update-game branch exists
        run: |
          if git ls-remote --heads origin update-game | grep -q "update-game"; then
            echo "Branch exists."
          else
            echo "Branch 'update-game' does not exist!" && exit 1
          fi

      # Update README to progress from step 2.1 to 2.2
      - name: Update to step 2.2
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2.1
          to_step: 2.2
          branch_name: update-game
